#!/bin/sh
set -e

if [ "$1" = configure ]; then
    if ! getent passwd pulse >/dev/null 2>&1; then
        useradd --system --user-group --no-create-home \
            --home-dir /nonexistent --shell /usr/sbin/nologin \
            --comment "pulse metrics server" pulse
    fi
fi

#DEBHELPER#
