[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
axum = "0.8.9"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
password-hash = { version = "0.5", features = ["getrandom"] }
protocol = { path = "../protocol" }
pulse-shared = { version = "0.1.0", path = "../pulse-shared" }
rpassword = "7"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate"] }
thiserror = "2"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
uuid = { version = "1", features = ["v4"] }
