[package]
name = "pulse-config"
version = "0.1.0"
edition = "2024"
license-file = "../../LICENSE"
publish = false

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.8"
thiserror = "2.0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pemfile = "2"
sha2 = "0.10"
